org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
neo_version=21.1.251
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=locomotion
mod_name=Locomotion
mod_license=All Rights Reserved
mod_version=0.1.12-fa-1.21.1
mod_group_id=com.trainguy9512.locomotion
