package com.trainguy9512.locomotion.config;

import com.trainguy9512.locomotion.LocomotionMain;
import com.trainguy9512.locomotion.animation.animator.JointAnimator;
import com.trainguy9512.locomotion.animation.animator.JointAnimatorRegistry;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import dev.isxander.yacl3.impl.controller.TickBoxControllerBuilderImpl;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.entity.BlockEntityType;

import java.text.DecimalFormat;
import java.util.Objects;

public class LocomotionConfigScreen {
    public static Screen createConfigScreen(Screen parentScreen) {

        LocomotionConfig config = LocomotionMain.CONFIG;
        config.load();

        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("locomotion.config.title"))
//                .category(ConfigCategory.createBuilder()
//                        .name(Component.translatable("locomotion.config.category.general.name"))
//                        .tooltip(Component.translatable("locomotion.config.category.general.tooltip"))
//                        .build())
                .category(firstPersonPlayerConfig(config))
                .category(blockEntitiesConfig(config))
                .save(config::save)
                .build()
                .generateScreen(parentScreen);
    }

    private static ConfigCategory firstPersonPlayerConfig(LocomotionConfig config) {
        return ConfigCategory.createBuilder()
                .name(Component.translatable("locomotion.config.category.first_person_player.name"))
                .tooltip(Component.translatable("locomotion.config.category.first_person_player.tooltip"))
                .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("locomotion.config.option.enable_first_person_renderer.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.option.enable_first_person_renderer.description"))
                                .build())
                        .binding(true, () -> config.data().firstPersonPlayer.enableRenderer, newValue -> config.data().firstPersonPlayer.enableRenderer = newValue)
                        .controller(option -> BooleanControllerBuilder.create(option)
                                .formatValue(state -> state ? Component.translatable("locomotion.config.option.enable_first_person_renderer.enabled") : Component.translatable("locomotion.config.option.enable_first_person_renderer.disabled"))
                                .coloured(true))
                        .build())
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("locomotion.config.group.first_person_camera_shake.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.group.first_person_camera_shake.description"))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_camera_shake_intensity_master.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_camera_shake_intensity_master.description"))
                                        .build())
                                .binding(1.0f, () -> config.data().firstPersonPlayer.cameraShakeMasterIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeMasterIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_camera_shake_intensity_movement.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_camera_shake_intensity_movement.description"))
                                        .build())
                                .binding(1.0f, () -> config.data().firstPersonPlayer.cameraShakeMovementIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeMovementIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_camera_shake_intensity_item_interactions.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_camera_shake_intensity_item_interactions.description"))
                                        .build())
                                .binding(0.5f, () -> config.data().firstPersonPlayer.cameraShakeItemInteractionIntensity, newValue -> config.data().firstPersonPlayer.cameraShakeItemInteractionIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .build())
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("locomotion.config.group.first_person_arm_camera_damping.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.group.first_person_arm_camera_damping.description"))
                                .build())
                        .option(Option.<Boolean>createBuilder()
                                .name(Component.translatable("locomotion.config.option.enable_first_person_arm_camera_damping.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.enable_first_person_arm_camera_damping.description"))
                                        .build())
                                .binding(true, () -> config.data().firstPersonPlayer.enableCameraRotationDamping, newValue -> config.data().firstPersonPlayer.enableCameraRotationDamping = newValue)
                                .controller(TickBoxControllerBuilderImpl::new)
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_arm_camera_stiffness_factor.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_arm_camera_stiffness_factor.description"))
                                        .build())
                                .binding(0.3f, () -> config.data().firstPersonPlayer.cameraRotationStiffnessFactor, newValue -> config.data().firstPersonPlayer.cameraRotationStiffnessFactor = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.01f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_arm_camera_damping_factor.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_arm_camera_damping_factor.description"))
                                        .build())
                                .binding(0.7f, () -> config.data().firstPersonPlayer.cameraRotationDampingFactor, newValue -> config.data().firstPersonPlayer.cameraRotationDampingFactor = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.01f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .build())
                .option(Option.<Float>createBuilder()
                        .name(Component.translatable("locomotion.config.option.first_person_mining_speed.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.option.first_person_mining_speed.description"))
                                .build())
                        .binding(1f, () -> config.data().firstPersonPlayer.miningAnimationSpeedMultiplier, newValue -> config.data().firstPersonPlayer.miningAnimationSpeedMultiplier = newValue)
                        .controller(option -> FloatSliderControllerBuilder.create(option)
                                .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                .range(0.25f, 2.00f)
                                .step(0.01f))
                        .build())
                .option(Option.<Float>createBuilder()
                        .name(Component.translatable("locomotion.config.option.running_arm_swing_intensity.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.option.running_arm_swing_intensity.description"))
                                .build())
                        .binding(1f, () -> config.data().firstPersonPlayer.runningArmSwingIntensity, newValue -> config.data().firstPersonPlayer.runningArmSwingIntensity = newValue)
                        .controller(option -> FloatSliderControllerBuilder.create(option)
                                .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                .range(0.00f, 1.00f)
                                .step(0.01f))
                        .build())
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("locomotion.config.group.first_person_map.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.group.first_person_map.description"))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_map_movement_animation_intensity.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_map_movement_animation_intensity.description"))
                                        .build())
                                .binding(0.2f, () -> config.data().firstPersonPlayer.mapMovementAnimationIntensity, newValue -> config.data().firstPersonPlayer.mapMovementAnimationIntensity = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.00").format(value)))
                                        .range(0.00f, 1.00f)
                                        .step(0.01f))
                                .build())
                        .build())
                .group(OptionGroup.createBuilder()
                        .name(Component.translatable("locomotion.config.group.first_person_arm_offset.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.group.first_person_arm_offset.description"))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_arm_offset_x.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_arm_offset_x.description"))
                                        .build())
                                .binding(0.0f, () -> config.data().firstPersonPlayer.armOffsetX, newValue -> config.data().firstPersonPlayer.armOffsetX = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(-16.00f, 16.00f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_arm_offset_y.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_arm_offset_y.description"))
                                        .build())
                                .binding(0.0f, () -> config.data().firstPersonPlayer.armOffsetY, newValue -> config.data().firstPersonPlayer.armOffsetY = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(-16.00f, 16.00f)
                                        .step(0.1f))
                                .build())
                        .option(Option.<Float>createBuilder()
                                .name(Component.translatable("locomotion.config.option.first_person_arm_offset_z.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.first_person_arm_offset_z.description"))
                                        .build())
                                .binding(0.0f, () -> config.data().firstPersonPlayer.armOffsetZ, newValue -> config.data().firstPersonPlayer.armOffsetZ = newValue)
                                .controller(option -> FloatSliderControllerBuilder.create(option)
                                        .formatValue(value -> Component.literal(new DecimalFormat("0.0").format(value)))
                                        .range(-16.00f, 16.00f)
                                        .step(0.1f))
                                .build())
                        .build())
                .build();
    }

    private static ConfigCategory blockEntitiesConfig(LocomotionConfig config) {
        ConfigCategory.Builder categoryBuilder = ConfigCategory.createBuilder();
        categoryBuilder.name(Component.translatable("locomotion.config.category.block_entities.name"));
        categoryBuilder.tooltip(Component.translatable("locomotion.config.category.block_entities.tooltip"));

        categoryBuilder.group(OptionGroup.createBuilder()
                .name(Component.translatable("locomotion.config.group.block_entity_optimization.name"))
                .description(OptionDescription.createBuilder()
                        .text(Component.translatable("locomotion.config.group.block_entity_optimization.description"))
                        .build())
                .option(Option.<Integer>createBuilder()
                                .name(Component.translatable("locomotion.config.option.block_entity_animation_distance.name"))
                                .description(OptionDescription.createBuilder()
                                        .text(Component.translatable("locomotion.config.option.block_entity_animation_distance.description"))
                                        .build())
                                .binding(32, () -> config.data().blockEntities.evaluationDistance, newValue -> config.data().blockEntities.evaluationDistance = newValue)
                                .controller(option -> IntegerSliderControllerBuilder.create(option)
                                        .range(4, 128)
                                        .step(4))
                                .build())
                .option(Option.<JointAnimator.PoseCalculationFrequency>createBuilder()
                        .name(Component.translatable("locomotion.config.option.block_entity_pose_calculation_frequency.name"))
                        .description(OptionDescription.createBuilder()
                                .text(Component.translatable("locomotion.config.option.block_entity_pose_calculation_frequency.description"))
                                .build())
                        .binding(JointAnimator.PoseCalculationFrequency.CALCULATE_EVERY_FRAME, () -> config.data().blockEntities.poseCalculationFrequency, newValue -> config.data().blockEntities.poseCalculationFrequency = newValue)
                        .controller(option -> EnumControllerBuilder.create(option)
                                .enumClass(JointAnimator.PoseCalculationFrequency.class)
                                .formatValue(v -> Component.translatable("locomotion.config.option.block_entity_pose_calculation_frequency.enum." + v.name().toLowerCase())))
                        .build())
                .build());

        OptionGroup.Builder blockTogglesBuilder = OptionGroup.createBuilder()
                .name(Component.translatable("locomotion.config.group.individual_block_entity_toggles.name"))
                .description(OptionDescription.createBuilder()
                        .text(Component.translatable("locomotion.config.group.individual_block_entity_toggles.description"))
                        .build());

        for (BlockEntityType<?> blockEntityType : JointAnimatorRegistry.getRegisteredBlockEntities()) {
            Identifier blockEntityTypeIdentifier = BlockEntityType.getKey(blockEntityType);
            assert blockEntityTypeIdentifier != null;
            blockTogglesBuilder.option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("block." + blockEntityTypeIdentifier.toLanguageKey()))
                            .binding(
                                    false,
                                    () -> config.data().blockEntities.enabledBlockEntities.getOrDefault(blockEntityTypeIdentifier.toString(), true),
                                    newValue -> config.data().blockEntities.enabledBlockEntities.put(blockEntityTypeIdentifier.toString(), newValue)
                            )
                            .controller(option -> BooleanControllerBuilder.create(option).coloured(true))
                    .build());
        }

        categoryBuilder.group(blockTogglesBuilder.build());
        return categoryBuilder.build();
    }
}
